[build]
  base = "" 
  publish = "public"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "10.2.3"
  NODE_ENV = "development"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
